version: '3'

services:
  unblockneteasemusic:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    expose:
      - 8080
    networks:
      - unblockneteasemusic

networks:
  unblockneteasemusic:
    driver: bridge